services:
    www:
        #image: httpd:alpine
        build: ./dockerfiles/httpd
        ports: 
            - "8787:80"
            - "8788:443"
        volumes:
            - "./www:/usr/local/apache2/htdocs"
            - "./conf/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf"
            #- "./conf/httpd/extra/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf"
            - "./conf/httpd/extra/:/usr/local/apache2/conf.d/extra/"
            - "./conf/httpd/httpdEscrol.conf:/usr/local/apache2/conf.d/httpdEscrol.conf"
            - "./conf/tls/server.crt:/usr/local/apache2/conf.d/server.crt"
            - "./conf/tls/server.key:/usr/local/apache2/conf.d/server.key"
            - "./conf/httpd/vhosts:/usr/local/apache2/conf.d/vhosts"
            - "./conf/httpd/letsencrypt:/etc/letsencrypt"
        restart: always
    php_8-1:
        build: ./dockerfiles/php
        #ports: # no necesito hacerlo publico
        #    - "9000:9000"
        volumes:
            - "./www:/usr/local/apache2/htdocs"
        restart: always
    #php_7:
    #    build: ./dockerfiles/php/7/
        #ports: # no necesito hacerlo publico
        #    - "9000:9000"
    #    volumes:
    #        - "./www:/usr/local/apache2/htdocs"
    #    restart: always
    ftp:
        #image: stilliard/pure-ftpd
        build: ./dockerfiles/ftp
        ports:
            - "21:21"
            - 30000-30009:30000-30009
        volumes: 
            - "./www:/home/pure-ftpd/"
            - "./conf/ftp/pure-ftpd.conf:/etc/pure-ftpd/pure-ftpd.conf"
            - "./conf/ftp/pureftpd.passwd:/etc/pure-ftpd/passwd/pureftpd.passwd"
            - "./conf/tls/server.pem:/etc/ssl/private/pure-ftpd.pem"
        environment:
# also for ssl/tls:
#       -ADDED_FLAGS: "--tls=2"
            #- ADDED_FLAGS= --tls=2 -d -d # TLS y logs
            - ADDED_FLAGS= --tls=2 # TLS
            #- ADDED_FLAGS= -d -d # Logs

        restart: always
    db:
        #image: mariadb:10.7
        build: ./dockerfiles/db
        #ports: # no necesito hacerlo publico
        #    - "3306:3306"
        environment:
            MARIADB_ROOT_PASSWORD: /run/secrets/db_root_pswd
        volumes:
            - "./conf/db/dump:/docker-entrypoint-initdb.d"
            - "./conf/db/cnf:/etc/mysql/conf.d"
            - "persistentDB:/var/lib/mysql"
        restart: always
    phpmyadmin:
        #image: phpmyadmin:5-fpm-alpine
        build: ./dockerfiles/phpmyadmin
        volumes:
            - "./conf/phpmyadmin/disablesecurity.conf:/usr/local/etc/php-fpm.d/disablesecurity.conf"
            - "./conf/phpmyadmin/config.inc.php:/var/www/html/config.inc.php"
        environment:
            MYSQL_ROOT_PASSWORD: /run/secrets/db_root_pswd # 3_b6NyyCz5YH!
        restart: always
        depends_on:
          - db
          - www
volumes:
    persistentDB:
secrets:
  db_root_pswd:
    file: ./conf/comun/db_root_pswd.txt
